### ISSUE TITLE
W3C does not provide a validator instance over SSL

### ISSUE THREAD

**Issue by renyard** [renyard/validity#33]
This is insecure for sites which could include sensitive data. The default should be secure.

New default/optional validator:
- Install a public instance with SSL cert and set default?
- Option to validate via URL, rather than fragment?

Keep data local and document via:
- Local install via MAMP/XAMPP?
- Virtual Machine?
- Docker? (mentioned in #32)

**Comment by renyard** [comment]
A validator instance has now been set up with SSL, scoring an [A in SSL Check](https://sslcheck.globalsign.com/en_GB/sslcheck/?host=html.validity.org.uk). This will replace the W3C instance as the default in the next version of Validity. While performance feels comparable to the W3C instance, there may be more [optimisations](38) that can be made.

Thanks to @magnetikonline for the Docker image used to set this up.

**Comment by magnetikonline** [comment]
:+1: thanks for the shoutout @renyard  :)

(and sorry for re-opening your ticket!).
