### ISSUE TITLE
Reports valid HTML5 when no <html> tag is present

### ISSUE THREAD

**Issue by multiwebinc** [renyard/validity#42]
This should be invalid, but it's not:

    <!DOCTYPE html>
    <head>
        <title>title</title>
    </head>
    <body>
    </body>
    </html>

**Comment by renyard** [comment]
HTML5 provides quite a lot of rules around error correction and as a result, this is a valid document.

The opening \<html\> tag can be emitted if the [first thing inside the element is not a comment](https://developer.mozilla.org/en-US/docs/Web/HTML/Element/html#Summary). In this case, the opening \<html\> is inferred by the opening \<head\> and so can be closed at the end.

Validating the document directly on the [W3C Validator](http://validator.w3.org) (Validity uses an instance of the W3C validator for it's validation) produces the same result.
