### ISSUE TITLE
Update to dockerhtmlvalidator

### ISSUE THREAD

**Issue by magnetikonline** [renyard/validity#43]
Hey @renyard .

Had no other means of contact for you - updated the HTML5 validator.nu version tonight to the April 2015 release.

https://github.com/magnetikonline/dockerhtml5validator/commit/a640db1a9f024644347b34a10020f70386a62129

Cheers

   Pete

**Comment by renyard** [comment]
Hi Pete

Thanks for the heads up. I'll have a look at testing and updating this later in the week.

**Comment by renyard** [comment]
Tasks:
- [ ] Check change log of validator.nu.
- [ ] Deploy new instance of validator and SSL reverse proxy.
- [ ] Test against a range of live web sites.
- [ ] Repoint live domain.
- [ ] Remove old instance.
