### ISSUE TITLE
Could not contact validator: Bad Gateway

### ISSUE THREAD

**Issue by darioalbanesi** [renyard/validity#45]
Trying to use the plugin and getting a "Could not contact validator: Bad Gateway" error on any website.

https://html.validity.org.uk/check is not reachable..

Is there any other option we could use?

Thanks
Cheers

**Comment by renyard** [comment]
Should be back up and running now.

You can change the validator host in the options to work around any downtime in the default validator. I'm looking into how I can improve uptime and monitoring on this, though.
