### ISSUE TITLE
Could not contact validator: Bad Gateway

### ISSUE THREAD

**Issue by kgajadhar** [renyard/validity#48]
Hi,

It seems that the validator service at 'https://html.validity.org.uk/check' is down.
Can it be brought back to life?
Perhaps an alternative?

Thanks in advance.
Regards.

p.s. great tool :)

**Comment by renyard** [comment]
Thanks for reporting, it's back up now.

Validity also supports using your own installation of the W3C Validator. If you install one locally, this is also likely to be faster as well as having the advantage of working offline.
