### ISSUE TITLE
Could not contact validator

### ISSUE THREAD

**Issue by walliby** [renyard/validity#49]
Love this plugin! Last couple days I have been getting error when I run it though: "Could not contact validator: Bad Gateway"

**Comment by brianlack** [comment]
Same here. Getting a 502 Bad Gateway error from https://html.validity.org.uk/check

**Comment by renyard** [comment]
It's back up now. Thank you both for reporting.

**Comment by ekosynth** [comment]
Same again.

**Comment by renyard** [comment]
Thanks for reporting @ekosynth. Not sure what happened there, but I've spun up a brand new server now. Give it a while for the DNS to propagate and it should be working again.

**Comment by renyard** [comment]
If you want to use Validity before the DNS propagates, you can set the validator URL to the new IP (https://178.62.8.7/check) in Validity's options. You will need load it in a normal browser tab first to accept the mismatch certificate (as the cert is signed against html.validity.org.uk).

This is NOT secure and the IP could change later, so make sure to switch it back ASAP and keep in mind the lower security and what data you are sending to the validator.
