### ISSUE TITLE
Could not contact validator: Bad Gateway

### ISSUE THREAD

**Issue by walliby** [renyard/validity#51]
I am getting an error when I try to validate my page... "Could not contact validator: Bad Gateway". Thanks

**Comment by NeilCrosby** [comment]
Confirmed that I'm also seeing this Ian. Fresh install, tested against both public and non public web pages.

**Comment by renyard** [comment]
Thank you both for reporting this. It's back up and running now.

**Comment by jego026** [comment]
This appears to be happening again.  I am getting a "Could not contact validator" error.

**Comment by renyard** [comment]
@jego026 Thanks for letting me know. It's back up now.
