### ISSUE TITLE
Validity server down again

### ISSUE THREAD

**Issue by kwein1** [renyard/validity#54]
Looks like it's unreachable again.  Whatever was fixed earlier today didn't take for long.

**Comment by renyard** [comment]
Are you still getting the bad gateway error? I've just checked and it's working for me now.

In order to confirm, are you able to load https://html.validity.org.uk in the browser?

**Comment by kwein1** [comment]
I can load that page, but when I insert my URL, I get this:
Service Unavailable

The server is temporarily unable to service your request due to maintenance downtime or capacity problems. Please try again later.

Apache/2.4.7 (Ubuntu) Server at html.validity.org.uk Port 80

**Comment by renyard** [comment]
I'm seeing the same issue when validating via URL, but direct input, which Validity uses, is working for me.

Looks like there is a problem either way, so I'll look to set up a new instance later today, which should solve this issue.

**Comment by renyard** [comment]
I've just set up a new instance of the validator service, so hopefully that should solve your issue. Please can you confirm?

It may take a couple of hours for the DNS to propagate, although it's looking like it's resolving to the new server (178.62.36.48) for me already, checking against Google DNS (8.8.8.8 & 8.8.4.4).

(I am still unable to validate by URL in the web interface, but I'm not sure if this is something that has worked in the past, as it's not used by Validity.)

**Comment by kwein1** [comment]
The new instance worked fine just now, thanks!
