### ISSUE TITLE
Suppress validator warning: This interface to HTML5 document checking is obsolete.

### ISSUE THREAD

**Issue by aral** [renyard/validity#58]
You’ve probably already seen this, but couldn’t find an issue on it. When I run the validator with the remote instance, I’m getting the following warning in the console:

`This interface to HTML5 document checking is obsolete. Use an interface to http://localhost:8888/html5/ instead.`

Will also try with my local validator instance once it’s finished installing.

**Comment by renyard** [comment]
Thanks for reporting this. I have been looking at the feasibility of moving from the legacy validator to the Nu Validator service in #44, but in the meantime, I think this warning could be suppressed, as it's not particularly helpful in this circumstance.

**Comment by renyard** [comment]
- [ ] Check for `obsolete-interface` message ID and remove from error list.
- [ ] Add test to ensure that the message count is zero in the event that this is the only message returned.

**Comment by renyard** [comment]
Released in v3.1.0.
