### ISSUE TITLE
Error: Could not contact validator: Bad Gateway

### ISSUE THREAD

**Issue by iport** [renyard/validity#59]
When attempting to validate localhost .htm page using Chrome Validity extension receive error "Could not contact validator: Bad Gateway". It was working yesterday without any problems. Tried for multiple sites / pages - same issue.

**Comment by renyard** [comment]
Thanks for reporting.

I've just got it back up and running, so it should be working again for you now.

**Comment by renyard** [comment]
Reopening. It's back up, but it's still not responding correctly.

**Comment by renyard** [comment]
OK, it's back up and responding correctly this time.

**Comment by iport** [comment]
Thanks!
