### ISSUE TITLE
No way to trigger validity in new icon-less toolbar

### ISSUE THREAD

**Issue by hyperknot** [renyard/validity#61]
Since a release ago, Chrome disabled all icons in the toolbar and moved them to the right side extension icons.

This means that there is no way to actually start validity. Please modify the UI so that the clicking on the icon should trigger a validity run instead of going to the plugin page.

**Comment by hyperknot** [comment]
Sorry, it might be because I tried to run on a file url.

**Comment by renyard** [comment]
Thanks for reporting and the quick clarification.

Previously, the icon would only show up for pages that Validity could validate. Now that it is always visible, it is likely to be quite confusing. I'll have a think about the best way to indicate this in the next update.
