### ISSUE TITLE
Default Validator

### ISSUE THREAD

**Issue by jamierytlewski** [renyard/validity#62]
Before I open a PR and everything, I was going to ask why the default server is: https://html.validity.org.uk/check and do you know who runs that server? The reason is that the current default is a bit out of date and causes some pages to not validate even though they are valid. 

https://github.com/validator/validator/issues/193

Thanks and this is a such a wonderful extension!

**Comment by renyard** [comment]
I run that server, which I set up primarily to implement HTTPS, which wasn't supported by the official W3C instance at the time. I also had reports of possible rate limiting on the W3C instance, which was causing a problem for some users.

The validation service is installed from the Ubuntu package, which unfortunately doesn't get updated all that often. I would recommend trying the official W3C instance (which I am considering reinstating as the default as it does now support HTTPS), by setting the validator URL to "https://validator.w3.org/check" in the Validity options page.

**Comment by renyard** [comment]
Default validator changed to the W3C instance in v3.2.0.
