### ISSUE TITLE
Server access broken

### ISSUE THREAD

**Issue by johnswolter** [renyard/validity#64]
I'm getting this error when requesting a page validation.  Chrome is up to date

Server web page:
Error 522 Ray ID: 29cce61b2b4b0436 • 2016-05-02 16:37:54 UTC
Connection timed out

Chrome JS console messages:

Failed to load resource: the server responded with a status of 522 ()
https://html.validity.org.uk/check 

Uncaught TypeError: Cannot read property 'statusText' of undefined  net.js:75 

Failed to load resource: the server responded with a status of 522 ()
https://html.validity.org.uk/check

Uncaught TypeError: Cannot read property 'statusText' of undefined   net.js:75 

Failed to load resource: the server responded with a status of 522 ()
https://html.validity.org.uk/check 

Uncaught TypeError: Cannot read property 'statusText' of undefined   net.js:75

**Comment by renyard** [comment]
Thanks for reporting. The validation service is back up now.
