### ISSUE TITLE
Could not contact validator

### ISSUE THREAD

**Issue by MikePSO** [renyard/validity#65]
Hi,

the addon can't connect to the validator for 2 days. It worked fine before. Any ideas on how to fix it?
![unbenannt-1](https://cloud.githubusercontent.com/assets/19549015/15498363/a5d40898-219f-11e6-9580-5a6b463b2574.jpg)

**Comment by renyard** [comment]
Thanks for reporting.

Looks like there was a problem on the server side. Should be working again for you now.

**Comment by henricavalcante** [comment]
I have the same problem right now =(

**Comment by renyard** [comment]
@henricavalcante In a recent update, I changed the default validator from one that I run to the W3C instance. Can you check that you are running at least v3.2.0, please? (You can find the version in Chrome's extensions page)

**Comment by MikePSO** [comment]
I'm on 3.2.1 with the same problem.

**Comment by renyard** [comment]
Thanks @henricavalcante and @MikePSO for reporting. Looks like there's been a breaking change to the W3C validator. I've just published a new version (v3.2.2), which is going back to using a working validator instance.

**Comment by MikePSO** [comment]
great job @renyard thanks a lot! 

Would it be possible to highlight errors in the source code? Since our code gets minified on the server, it's really hard to see where exactly the errors are.
