### ISSUE TITLE
Not responding !!!

### ISSUE THREAD

**Issue by nvandersangen** [renyard/validity#66]
Tried multiple times today, but nothing happens.
Loader-icons stops & alert-icon appears: "Could not contact validator:".

@renyard Plz fix this awesome tool!

![validity-error](https://cloud.githubusercontent.com/assets/15786788/15959089/43e8b342-2ef9-11e6-915c-2761cffce5ef.jpg)

**Comment by renyard** [comment]
Thanks for reporting. It should be working again now.

**Comment by nvandersangen** [comment]
Hate to bring it, but error still occurs occasionally :S

**Comment by renyard** [comment]
No problem, thanks again for reporting.

I'm trying to get the server back up and running now. In the meantime, can you try updating the validator URL to https://validator.w3.org/check in the validity options? You can get to the options through the icon's right click menu. Please let me know how you get on, as I am considering changing the default to avoid these issues.

**Comment by nvandersangen** [comment]
Sure: URL is applied. Seems to be working again :)

![validity-update](https://cloud.githubusercontent.com/assets/15786788/15964678/f86f66ce-2f19-11e6-8d39-5a2c1b4d52bb.jpg)
