### ISSUE TITLE
404 page cannot be validated

### ISSUE THREAD

**Issue by adcostache** [renyard/validity#68]
I'm trying to validate a Wordpress 404 page with this plugin, however it seems not to work.

In this case, not working means the loading icon in Chrome version 51.0.2704.103 m keeps animating for some time (30 seconds to 1 minute) and then it freezes.

Is there some thing I could to do overcome this? To this point it looks like a bug but maybe there's something I'm doing wrong.

Thanks!

**Comment by renyard** [comment]
Thanks for reporting this. I've just deployed v3.2.0 with a fix for this and you should now be able to successfully validate pages with an HTTP response other than 200.

I'm rolling the update out gradually to existing users. If you want the update immediately, you may need to force a reinstall of the extension from the Chrome Web Store by uninstalling and then reinstalling from https://chrome.google.com/webstore/detail/validity/bbicmjjbohdfglopkidebfccilipgeif.
