### ISSUE TITLE
Error contacting validator

### ISSUE THREAD

**Issue by nvandersangen** [renyard/validity#69]
Hi renyard,

Currently unable to use the extension:
![validity-error_2016-09-13](https://cloud.githubusercontent.com/assets/15786788/18467948/1dacc3f0-79a2-11e6-94b0-5c0049af3400.png)

Plz fix :)

**Comment by renyard** [comment]
Hi @nvandersangen

There was a recent change in the W3C hosted validator which has broken compatibility with this extension. I am looking to fix this in the near future, but in the meantime, if you go into Validity settings and unset the custom validator setting, you should find that it works again.

**Comment by ismaail** [comment]
Please reopen this issue if not fixed yet.
