### ISSUE TITLE
Clicking on icon in toolbar results in dropdown menu. Cannot activate validator.

### ISSUE THREAD

**Issue by Bshally** [renyard/validity#71]
Clicking on the icon will not open the validator. Cannot activate through the key commands either. Any thoughts?

![screen shot 2016-10-03 at 10 06 35 am](https://cloud.githubusercontent.com/assets/3440317/19040197/1d4ee852-8951-11e6-9e7e-ce10676759da.png)

**Comment by renyard** [comment]
Hi @Bshally

Is this happening immediately after installing the extension? You will need to refresh any existing tabs after installation before the extension will be available. (Also, extensions will not work on the Chrome Web Store for security reasons.)

Thanks
