### ISSUE TITLE
Add the Emulated Device's User-Agent when fetching the page for validation or use current HTML instead of fetch

### ISSUE THREAD

**Issue by bjornbak** [renyard/validity#72]
We am developing an adaptable design (not RWD) so our server is not returning the same html for mobile and desktop devices. We detect the device from the User-Agent and return the correct version from the same URL.

We the brilliant device emulator in Chrome to do (preliminary) tests.

Now we want the pages valid too and found your excellent extension.

The problem when I am emulating a mobile and validate it is the desktop version that is validated.

Please include the current emulated device (User-Agent) when fetching the page for validation or even better grap the html currently showing the Chrome because that would make it possible to validate the HTML after Ajax calls etc.

You must be fetching the request because I can validate fixes only on the webserver on localhost.

**Comment by renyard** [comment]
Hi
Thanks for raising this.

> Please include the current emulated device (User-Agent) when fetching the page for validation

Changing the User Agent via the Dev Tools will only make the change to the current tab, where as Validity's request comes from the plugin process, picking up the default User Agent.

It may be possible to get the User Agent from the page and set it on Validity's request, but I don't think this is something that I am interested in implementing as I don't think serving different content based on User Agent is a common use case (or something I'll use myself). I am, however, open to pull requests on this, provided it doesn't add too much maintenance overhead.

> grap the html currently showing the Chrome because that would make it possible to validate the HTML after Ajax calls etc.

This feature has been requested several times, but would result in validating HTML that had been parsed and then serialized by Chrome. There's no guarantee that this would bear much resemblance to your initial HTML.

> You must be fetching the request because I can validate fixes only on the webserver on localhost.

Validity does make it's own request to get the source of the page. I have investigated ways to get it from the initial request, which is the ultimate answer to this issue, but Chrome does not provide a way to do that in an extension.
