### ISSUE TITLE
It's Not Available for local pages

### ISSUE THREAD

**Issue by shalaby1** [renyard/validity#76]
I do templates on my pc  but locally without any other hosting but the " validator icon " is not available for many websites " online " and never available for local websites " the ones I creat " .

**Comment by renyard** [comment]
Thanks for raising this issue.

Validating pages from the local file system is not currently supported. It's something I'd like to add, but I don't think it's going to be possible to do without a large rewrite of the code, which I'm not going to have the time to complete in the near future. The only workaround I can suggest is using a basic local webserver and loading it from that.

As for online sites, you should be able to validate any page with a URL starting http:// or https://, with the exception of the Chrome Web Store (on which all extensions are disabled). If you are unable to validate other sites, please can you reopen this issue and let me know the full URL of the site and a quick description of the steps that you've gone through in attempting to validate it?
