### ISSUE TITLE
Extension kicked from Chrome Webstore

### ISSUE THREAD

**Issue by bennyborn** [renyard/validity#79]
Are there any plans to bring this extension back into Chrome Webstore?

**Comment by MuhammadMabrouk** [comment]
Any updates on this?

**Comment by eu6en** [comment]
Any suggestions why this has happened?

**Comment by marknotton** [comment]
> Any suggestions why this has happened?

I believe the developer (@renyard) will have been notified before it was taken down. Likely a new security violation that only came into play long after the initial release of the extension. I'm only speculating, but from my experience this could mean anything from a fundmental rebuild to appease Googles updated list of requiremnets -- or something arbitory like a privacy notice needing be added somewhere.

In any case, I would love to see this come back. There are no alternative extensions that compare this one.

**Comment by renyard** [comment]
Thanks for the interest and appoloiges that it's taken a while for me to get round to this. The issue was that the extension was requesting tabs permissions, which it wasn't using. I've submitted an update, so hopefully this will pass the Google review and be in the Chrome Web Store soon. 🤞
