### ISSUE TITLE
Wrong type of message

### ISSUE THREAD

**Issue by chefranov** [renyard/validity#80]
When I check my page I got errors in the extension:

![image](https://user-images.githubusercontent.com/2775475/195564567-781aaca0-d9a7-46fc-8968-e6ceda7e9401.png)

But if I check it on w3c validator site I got "Info" (not error).

![image](https://user-images.githubusercontent.com/2775475/195564769-7af649cf-a449-4f71-87aa-6422316b7030.png)

Can you change type of message from Error to Info?

UPD: PR with fixes - #81

**Comment by peter-neumann-dev** [comment]
+1 essential
I would be happy too 🙏

**Comment by chefranov** [comment]
I think @renyard no longer supports this extension :(

**Comment by peter-neumann-dev** [comment]
It seems so, unfortunately, I don't know a solution to fix that myself.

**Comment by chefranov** [comment]
It's easy to fix, but then need to build and use this extension only locally (not from store)

**Comment by renyard** [comment]
Thanks for reporting this. The extension is not under active development, but I’m happy to release bug fixes.

It was the intention to take the log level into account and I’m pretty sure this used to work. I’ve not had a chance to dig into it, so I’m not sure why that’s not working anymore. @chefranov If you have a fix, please do raise a PR and I will test and release to the store as soon as I can.

**Comment by chefranov** [comment]
@renyard check PR please - #81

**Comment by chefranov** [comment]
In Chrome by default you can't see Info messages. If want to see it you need to mark Info from dropdown.

![image](https://user-images.githubusercontent.com/2775475/199312226-46db6e6c-7ed8-4aa6-8617-5d59a781b3b8.png)

**Comment by chefranov** [comment]
@renyard did you get a chance to check PR?

**Comment by renyard** [comment]
@chefranov Looks good from the PR, thanks for submitting it. I’ve not had a chance to test and build it for release yet though. I hope to get some time to sort that out over the weekend. I’ll update here once it’s been released to the store.

**Comment by renyard** [comment]
I've just landed the PR and submitted to the Chrome Web Store. All going well, it should start rolling out to users once it's been approved in the next couple of days.

@chefranov Thanks again for submitting this PR, it's much appreciated by myself and Validity users. 🎉

I'll leave this ticket open until we've confirmed that it's been released to the store.

**Comment by chefranov** [comment]
Appeared in the store. For me works fine. @peter-neumann-dev can you check from your side?

**Comment by peter-neumann-dev** [comment]
@chefranov Yes, it's working fine! Thank you, both 👏
